name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_DIR: Apps/lightnovelpub
  APP_NAME: "LightNovel Pub"
  BUNDLE_ID: "com.alot1z.lightnovelpub"

jobs:
  build:
    name: Build Release
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Build Tools
      run: |
        brew install imagemagick
        sudo xcode-select -s /Applications/Xcode.app
          
    - name: Generate App Icons
      run: |
        cd Apps/lightnovelpub
        chmod +x scripts/generate_icons.sh
        ./scripts/generate_icons.sh assets/icon.png
          
    - name: Build iOS App
      run: |
        cd Apps/lightnovelpub
        chmod +x scripts/build.sh
        ./scripts/build.sh \
          --ios-version 17.0 \
          --app-version 1.0.0 \
          --min-ios-version 16.0 \
          --max-ios-version 17.0 \
          --optimization-level 3 \
          --enable-bitcode false \
          --enable-arc true \
          --deployment-target 16.0 \
          --entitlements com.apple.security.network.client,com.apple.security.network.server,com.apple.private.security.no-container,com.apple.developer.usernotifications.time-sensitive,com.apple.developer.default-data-protection \
          --features reader_mode,offline_storage,chapter_download,push_notifications,dark_mode,custom_themes,ios17_features \
          --dependencies WebKit,SafariServices,UserNotifications,SwiftUI
        
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: LightNovelPub.ipa
        path: Apps/lightnovelpub/build/LightNovelPub.ipa
