#!/bin/sh

# Set permissions
chmod 6755 /Applications/TrollStore.app/TrollStore
chmod 6755 /Applications/TrollStore.app/TrollHelperOTA
chmod 644 /Applications/TrollStore.app/Info.plist

# Copy entitlements
cp -f /Applications/TrollStore.app/entitlements.plist /var/mobile/Library/Preferences/

# Reload preferences
killall -9 cfprefsd

# Restart SpringBoard
killall -9 SpringBoard

exit 0
