name: Build Android Emulator IPA

on:
  push:
    paths:
      - 'Apps/AndroidEmulator/**'
      - '.github/workflows/android-emulator.yml'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  BUNDLE_ID: "com.alot1z.androidemulator"
  APP_NAME: "Android Emulator"

jobs:
  build:
    name: Build Android Emulator IPA
    runs-on: macos-latest
    
    defaults:
      run:
        working-directory: Apps/AndroidEmulator

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Set up build directory
      run: |
        mkdir -p build/AndroidEmulator.xcarchive/Products/Applications
        
    - name: Build unsigned app
      run: |
        cd Apps/AndroidEmulator
        xcodebuild -project AndroidEmulator.xcodeproj \
          -scheme AndroidEmulator \
          -configuration Release \
          -archivePath ../../build/AndroidEmulator.xcarchive \
          -destination 'generic/platform=iOS' \
          -sdk iphoneos \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Package IPA
      run: |
        cd build/AndroidEmulator.xcarchive/Products/Applications
        mkdir Payload
        cp -r AndroidEmulator.app Payload/
        zip -r AndroidEmulator.ipa Payload
        rm -rf Payload
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: AndroidEmulator-unsigned
        path: build/AndroidEmulator.xcarchive/Products/Applications/AndroidEmulator.ipa
        retention-days: 5
