name: 📱 Android Emulator Build

on:
  push:
    branches: [ main ]
    paths:
      - 'Apps/AndroidEmulator/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Apps/AndroidEmulator/**'
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  ANDROID_NDK_VERSION: '25.2.9519653'
  ANDROID_SDK_TOOLS_VERSION: '9477386'
  ANDROID_PLATFORM_VERSION: '33'
  CCACHE_DIR: ~/.ccache
  GRADLE_USER_HOME: ~/.gradle

jobs:
  build:
    name: Build Android Emulator
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-
          
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build with Gradle
      working-directory: Apps/AndroidEmulator
      run: |
        # Enable ccache
        export CC="ccache gcc"
        export CXX="ccache g++"
        export CCACHE_CPP2=yes
        
        # Give gradle more memory
        export GRADLE_OPTS="-Xmx4g -Dorg.gradle.daemon=false"
        
        # Build with all optimizations
        ./gradlew assembleRelease \
          --no-daemon \
          --parallel \
          --build-cache \
          --configure-on-demand \
          --max-workers=$(nproc) \
          -Dkotlin.compiler.execution.strategy=in-process \
          -Dkotlin.incremental=true \
          -Dkotlin.incremental.useClasspathSnapshot=true \
          -Pandroid.enableR8.fullMode=true \
          -Pandroid.enableD8.desugaring=true \
          -Pandroid.enableBuildCache=true \
          -Pandroid.enableProfileJson=true
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-emulator
        path: Apps/AndroidEmulator/app/build/outputs/apk/release/*.apk
        retention-days: 5
