name: Build Android Emulator

on:
  push:
    branches: [ main ]
    paths:
      - 'Apps/AndroidEmulator/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Apps/AndroidEmulator/**'
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  ANDROID_NDK_VERSION: '25.2.9519653'
  ANDROID_SDK_TOOLS_VERSION: '9477386'
  ANDROID_PLATFORM_VERSION: '33'
  CCACHE_DIR: ~/.ccache
  GRADLE_USER_HOME: ~/.gradle

jobs:
  build-emulator:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        lfs: true
    
    # Setup Java with Gradle caching
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        cache: 'gradle'
    
    # Setup Gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true
    
    # Setup ccache
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: 2G
    
    # Setup build cache
    - name: Cache Build
      uses: actions/cache@v3
      with:
        path: |
          ~/.ccache
          ~/.gradle
          ~/.android/build-cache
          build/
          .build/
          Apps/AndroidEmulator/.gradle
          Apps/AndroidEmulator/app/build
        key: android-${{ hashFiles('Apps/AndroidEmulator/**') }}
        restore-keys: |
          android-
    
    # Setup Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}
        cmdline-tools-version: ${{ env.ANDROID_SDK_TOOLS_VERSION }}
    
    # Build with Gradle
    - name: Build Android Emulator
      working-directory: Apps/AndroidEmulator
      run: |
        # Enable ccache
        export CC="ccache gcc"
        export CXX="ccache g++"
        export CCACHE_CPP2=yes
        
        # Give gradle more memory
        export GRADLE_OPTS="-Xmx4g -Dorg.gradle.daemon=false"
        
        # Build with all optimizations
        ./gradlew assembleRelease \
          --no-daemon \
          --parallel \
          --build-cache \
          --configure-on-demand \
          --max-workers=$(nproc) \
          -Dkotlin.compiler.execution.strategy=in-process \
          -Dkotlin.incremental=true \
          -Dkotlin.incremental.useClasspathSnapshot=true \
          -Pandroid.enableR8.fullMode=true \
          -Pandroid.enableD8.desugaring=true \
          -Pandroid.enableBuildCache=true \
          -Pandroid.enableProfileJson=true
    
    # Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-emulator
        path: Apps/AndroidEmulator/app/build/outputs/apk/release/*.apk
        retention-days: 5
