name: Build Android Emulator IPA

on:
  push:
    paths:
      - 'Apps/AndroidEmulator/**'
      - '.github/workflows/android-emulator.yml'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  BUNDLE_ID: "com.alot1z.androidemulator"
  APP_NAME: "Android Emulator"

jobs:
  build:
    name: Build Android Emulator IPA
    runs-on: macos-latest
    
    defaults:
      run:
        working-directory: Apps/AndroidEmulator

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Debug directory structure
      run: |
        pwd
        ls -la
        ls -la Apps || echo "Apps directory not found"
    
    - name: Set up build directory
      run: |
        mkdir -p build
        
    - name: Build unsigned app
      working-directory: ${{ github.workspace }}/Apps/AndroidEmulator
      run: |
        xcodebuild -project AndroidEmulator.xcodeproj \
          -scheme AndroidEmulator \
          -configuration Release \
          -archivePath ${{ github.workspace }}/build/AndroidEmulator.xcarchive \
          -destination 'generic/platform=iOS' \
          -sdk iphoneos \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Package IPA
      working-directory: ${{ github.workspace }}/build/AndroidEmulator.xcarchive/Products/Applications
      run: |
        mkdir -p Payload
        cp -r AndroidEmulator.app Payload/
        zip -r AndroidEmulator.ipa Payload
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: AndroidEmulator-unsigned
        path: ${{ github.workspace }}/build/AndroidEmulator.xcarchive/Products/Applications/AndroidEmulator.ipa
        retention-days: 5
