name: Android Emulator Build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Apps/AndroidEmulator/**'
      - '.github/workflows/android-emulator.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Apps/AndroidEmulator/**'
      - '.github/workflows/android-emulator.yml'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  BUNDLE_ID: "com.alot1z.androidemulator"
  APP_NAME: "Android Emulator"

jobs:
  build:
    name: Build Android Emulator IPA
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Apps/AndroidEmulator

    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Install Dependencies
      run: |
        brew install xcbeautify

    - name: Build App
      run: |
        xcodebuild -project AndroidEmulator.xcodeproj \
          -scheme AndroidEmulator \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath build/AndroidEmulator.xcarchive \
          clean archive CODE_SIGNING_ALLOWED=NO | xcbeautify
          
    - name: Create IPA
      run: |
        cd build/AndroidEmulator.xcarchive/Products/Applications
        mkdir Payload
        cp -r *.app Payload/
        zip -r AndroidEmulator.ipa Payload
        mv AndroidEmulator.ipa ../../../
          
    - name: Upload Android Emulator IPA
      uses: actions/upload-artifact@v4
      with:
        name: AndroidEmulator-Unsigned
        path: Apps/AndroidEmulator/build/AndroidEmulator.ipa
        retention-days: 5
