name: Android Emulator Build

on:
  push:
    branches: [ main ]
    paths:
      - 'Apps/AndroidEmulator/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Apps/AndroidEmulator/**'
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  GRADLE_VERSION: '8.5'
  ANDROID_SDK_TOOLS_VERSION: '9477386'
  ANDROID_PLATFORM_VERSION: '34'
  ANDROID_BUILD_TOOLS_VERSION: '34.0.0'
  ANDROID_NDK_VERSION: '26.1.10909125'
  CCACHE_DIR: ~/.ccache

jobs:
  build:
    name: Build Android Emulator
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: ${{ env.ANDROID_SDK_TOOLS_VERSION }}
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ env.GRADLE_VERSION }}
        cache-read-only: false
        gradle-home-cache-cleanup: true
        
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: 2G
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-
          
    - name: Cache Gradle and Build
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
          Apps/AndroidEmulator/.gradle
          Apps/AndroidEmulator/app/build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Accept Android Licenses
      run: yes | sdkmanager --licenses
        
    - name: Install Android Components
      run: |
        sdkmanager --install \
          "platforms;android-${{ env.ANDROID_PLATFORM_VERSION }}" \
          "build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}" \
          "ndk;${{ env.ANDROID_NDK_VERSION }}"
          
    - name: Setup Build Environment
      run: |
        cd Apps/AndroidEmulator
        chmod +x ./gradlew
        # Configure ccache
        export CCACHE_EXEC=$(which ccache)
        export NDK_CCACHE=$CCACHE_EXEC
        export USE_CCACHE=1
        ccache -M 5G
        ccache -o compression=true
        ccache -o compression_level=9
        
    - name: Build with Gradle
      run: |
        cd Apps/AndroidEmulator
        ./gradlew assembleDebug \
          --no-daemon \
          --parallel \
          --build-cache \
          --configure-on-demand \
          --max-workers=$(nproc) \
          -Dorg.gradle.caching=true \
          -Dorg.gradle.parallel=true \
          -Dorg.gradle.configureondemand=true \
          -Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError" \
          -Pandroid.useAndroidX=true \
          -Pandroid.enableJetifier=true \
          -Pandroid.enableR8.fullMode=true \
          -Pandroid.enableD8.desugaring=true \
          -Pandroid.enableBuildCache=true \
          -Pandroid.enableProfileJson=true
          
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AndroidEmulator-debug
        path: Apps/AndroidEmulator/app/build/outputs/apk/debug/app-debug.apk
