name: Build Android Emulator

on:
  push:
    branches: [ main ]
    paths:
      - 'Apps/AndroidEmulator/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Apps/AndroidEmulator/**'
  workflow_dispatch:

env:
  ANDROID_NDK_VERSION: 25.2.9519653
  ANDROID_SDK_TOOLS_VERSION: 9477386
  ANDROID_PLATFORM_VERSION: 33
  JAVA_VERSION: 17
  CCACHE_DIR: ~/.ccache
  GRADLE_USER_HOME: ~/.gradle

jobs:
  build-emulator:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        lfs: true
    
    # Setup ccache
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: 2G
    
    # Setup build cache
    - name: Cache Build
      uses: actions/cache@v3
      with:
        path: |
          ~/.ccache
          ~/.gradle
          ~/.android/build-cache
          build/
          .build/
          Apps/AndroidEmulator/.gradle
          Apps/AndroidEmulator/app/build
        key: android-${{ hashFiles('Apps/AndroidEmulator/**') }}
        restore-keys: |
          android-
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        cache: 'gradle'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}
        cmdline-tools-version: ${{ env.ANDROID_SDK_TOOLS_VERSION }}
    
    - name: Build Android Emulator
      run: |
        cd Apps/AndroidEmulator
        
        # Enable ccache
        export CC="ccache gcc"
        export CXX="ccache g++"
        
        # Build with maximum optimization
        ./gradlew assembleRelease \
          -Dorg.gradle.parallel=true \
          -Dorg.gradle.workers.max=$(nproc) \
          -Dorg.gradle.caching=true \
          -Dkotlin.incremental=true \
          -Dkotlin.incremental.useClasspathSnapshot=true \
          -Pandroid.enableR8.fullMode=true \
          -Pandroid.enableD8.desugaring=true \
          -Pandroid.enableBuildCache=true \
          -Pandroid.enableProfileJson=true \
          -Pandroid.enableAppCompileTimeRClass=true \
          -Pandroid.experimental.enableSourceSetPathsMap=true \
          -Pandroid.experimental.cacheCompileLibResources=true
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-emulator
        path: Apps/AndroidEmulator/app/build/outputs/apk/release/*.apk
        retention-days: 5
