name: Build TrollStore Enhanced

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    env:
      THEOS: ${{ github.workspace }}/theos
      THEOS_DEVICE_IP: 127.0.0.1
      THEOS_DEVICE_PORT: 22
      SDK_VERSION: "17.0"
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Install Dependencies
      run: |
        brew install ldid make xz dpkg || true
        brew install wget || true
        
    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $THEOS
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip -d $THEOS/sdks
        mv $THEOS/sdks/sdks-master/*.sdk $THEOS/sdks/
        rm -rf master.zip $THEOS/sdks/sdks-master
        curl -LO https://github.com/theos/theos/archive/refs/heads/master.zip
        unzip master.zip
        cp -r theos-master/* $THEOS/
        rm -rf master.zip theos-master
        
    - name: Install Additional Tools
      run: |
        git clone https://github.com/sbingner/llvm-project
        cd llvm-project
        sudo xcode-select --switch /Applications/Xcode.app
        mkdir build && cd build
        cmake -G Ninja ../llvm \
          -DLLVM_ENABLE_PROJECTS="clang;lld" \
          -DCMAKE_BUILD_TYPE=Release
        ninja
        sudo ninja install
        cd ../..
        rm -rf llvm-project
        
    - name: Build Package
      run: |
        make package FINALPACKAGE=1
        
    - name: Create IPA
      run: |
        cd packages
        for deb in *.deb; do
          dpkg-deb -R "$deb" extracted
          mkdir -p Payload
          cp -r extracted/Applications/* Payload/ || true
          cp -r extracted/Library Payload/TrollStore.app/ || true
          zip -r "${deb%.*}.ipa" Payload
          rm -rf extracted Payload
          ldid -S../entitlements.plist "${deb%.*}.ipa"
        done
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TrollStoreEnhanced
        path: |
          packages/*.ipa
          packages/*.deb
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          packages/*.ipa
          packages/*.deb
        name: TrollStore Enhanced ${{ github.sha }}
        tag_name: v${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
