name: Build TrollStore Enhanced

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    env:
      THEOS: ${{ github.workspace }}/theos
      THEOS_DEVICE_IP: 127.0.0.1
      THEOS_DEVICE_PORT: 22
      SDK_VERSION: "17.0"
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Install Dependencies
      run: |
        brew install ldid make xz dpkg || true
        brew install wget cmake ninja || true
        sudo xcode-select --switch /Applications/Xcode.app
        
    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $THEOS
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip -d $THEOS/sdks
        mv $THEOS/sdks/sdks-master/*.sdk $THEOS/sdks/
        rm -rf master.zip $THEOS/sdks/sdks-master
        
    - name: Build TrollStore
      run: |
        chmod +x bins/build_enhanced.sh
        ./bins/build_enhanced.sh
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TrollStoreEnhanced
        path: |
          packages/*.ipa
          packages/*.deb
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          packages/*.ipa
          packages/*.deb
        name: TrollStore Enhanced ${{ github.sha }}
        tag_name: v${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
