name: Build TrollStore Enhanced

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  THEOS: /opt/theos
  THEOS_DEVICE_IP: 127.0.0.1
  THEOS_DEVICE_PORT: 22
  XCODE_VERSION: "14.2"

jobs:
  build:
    name: Build and Analyze
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/Homebrew
          ${{ env.THEOS }}/sdks
          ~/.theos
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-deps-${{ hashFiles('**/Makefile') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-deps-${{ hashFiles('**/Makefile') }}-
          ${{ runner.os }}-deps-

    - name: Install Dependencies
      run: |
        set -e
        brew update
        brew install ldid make theos dpkg xz
        brew cleanup

    - name: Setup Build Environment
      run: |
        set -e
        mkdir -p $THEOS/sdks
        if [ ! -d "$THEOS/sdks/iPhoneOS16.2.sdk" ]; then
          echo "Downloading iOS SDK..."
          curl -L https://github.com/theos/sdks/archive/master.zip -o master.zip
          unzip -q master.zip -d $THEOS/sdks
          mv $THEOS/sdks/sdks-master/*.sdk $THEOS/sdks/
          rm -rf master.zip $THEOS/sdks/sdks-master
        fi
        
    - name: Verify Environment
      run: |
        set -e
        echo "Xcode Version:"
        xcodebuild -version
        echo "Theos Version:"
        $THEOS/bin/update-theos || true
        echo "SDK List:"
        ls -la $THEOS/sdks/
        echo "Environment Variables:"
        env | grep -E "THEOS|DEVELOPER_DIR"

    - name: Build TrollStore
      run: |
        set -e
        export PATH="/opt/homebrew/bin:$PATH"
        export FINALPACKAGE=1
        export THEOS_PACKAGE_SCHEME=rootless
        
        # Build main project
        echo "Building main project..."
        make clean
        if [ "${{ github.event.inputs.build_type }}" = "debug" ]; then
          make package DEBUG=1
        else
          make package FINALPACKAGE=1
        fi
        
        # Check build success
        if [ ! -d "packages" ]; then
          echo "Error: Build failed - packages directory not found"
          exit 1
        fi

    - name: Build Extensions
      run: |
        set -e
        cd extensions || exit 1
        for ext in */; do
          if [ -f "$ext/Makefile" ]; then
            echo "Building extension: $ext"
            cd "$ext"
            make clean
            if [ "${{ github.event.inputs.build_type }}" = "debug" ]; then
              make package DEBUG=1
            else
              make package FINALPACKAGE=1
            fi
            cd ..
          fi
        done

    - name: Run Code Analysis
      run: |
        set -e
        echo "Running code analysis..."
        xcodebuild clean analyze \
          -scheme TrollStore \
          -destination "platform=iOS Simulator,OS=latest,name=iPhone 14" \
          ONLY_ACTIVE_ARCH=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -quiet \
          COMPILER_INDEX_STORE_ENABLE=NO || true

    - name: Run Tests
      run: |
        set -e
        echo "Running tests..."
        if [ -f "Makefile.test" ]; then
          make -f Makefile.test test
        fi
        
    - name: Package Artifacts
      run: |
        set -e
        mkdir -p artifacts
        
        # Copy main package
        if [ -d "packages" ]; then
          cp packages/*.deb artifacts/
        fi
        
        # Copy extension packages
        find extensions -name "*.deb" -exec cp {} artifacts/ \;
        
        # Create version info
        git describe --tags --always > artifacts/version.txt
        date > artifacts/build_date.txt
        
        # Create checksums
        cd artifacts
        shasum -a 256 *.deb > SHA256SUMS.txt
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore-Enhanced-Build-${{ github.sha }}
        path: |
          artifacts/*.deb
          artifacts/version.txt
          artifacts/build_date.txt
          artifacts/SHA256SUMS.txt
        if-no-files-found: error
        retention-days: 90

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*.deb
          artifacts/SHA256SUMS.txt
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
