name: Build TrollStore Enhanced

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    env:
      THEOS: /opt/theos
      THEOS_DEVICE_IP: 127.0.0.1
      THEOS_DEVICE_PORT: 22
      SDK_VERSION: "17.0"
      
      # Build Configuration
      FINALPACKAGE: 1
      DEBUG: 0
      
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Setup Build Environment
      run: |
        brew install ldid || true
        brew install make || true
        brew install xz || true
        brew install dpkg || true
        git clone --recursive https://github.com/theos/theos.git $THEOS
        
    - name: Install iOS SDK
      run: |
        mkdir -p $THEOS/sdks
        curl -LO https://github.com/theos/sdks/archive/master.zip
        unzip master.zip
        mv sdks-master/iPhoneOS${{ env.SDK_VERSION }}.sdk $THEOS/sdks/
        rm -rf master.zip sdks-master
        
    - name: Configure Build
      run: |
        mkdir -p packages
        chmod +x $THEOS/bin/*
        $THEOS/bin/update-theos
        
    - name: Build Package
      run: |
        export SDKVERSION=${{ env.SDK_VERSION }}
        export SYSROOT=$THEOS/sdks/iPhoneOS${{ env.SDK_VERSION }}.sdk
        make package FINALPACKAGE=1
        
    - name: Sign IPA
      run: |
        cd packages
        for deb in *.deb; do
          dpkg-deb -R "$deb" extracted
          mkdir -p Payload
          mv extracted/Applications/* Payload/ || true
          cp -r extracted/Library Payload/TrollStore.app/ || true
          zip -r "${deb%.*}.ipa" Payload
          rm -rf extracted Payload
          ldid -S../entitlements.plist "${deb%.*}.ipa"
        done
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TrollStoreEnhanced
        path: |
          packages/*.ipa
          packages/*.deb
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          packages/*.ipa
          packages/*.deb
        name: TrollStore Enhanced ${{ github.sha }}
        tag_name: v${{ github.run_number }}
        body: |
          TrollStore Enhanced Build ${{ github.sha }}
          
          Changes in this build:
          - Full iOS 17.0 Support
          - Enhanced Security Features
          - Improved Performance
          - Extended System Integration
          - Sileo Integration
          
          Installation:
          1. Download TrollStoreEnhanced.ipa
          2. Install using TrollStore
          3. Grant required permissions
          
          Note: This build includes all Sileo and system integrations
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
