name: LightNovel Pub Build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Apps/lightnovelpub/**'
      - '.github/workflows/lightnovelpub.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Apps/lightnovelpub/**'
      - '.github/workflows/lightnovelpub.yml'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  BUNDLE_ID: "com.alot1z.lightnovelpub"
  APP_NAME: "LightNovel Pub"
  MIN_IOS: "16.0"
  MAX_IOS: "17.0"

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Apps/lightnovelpub

    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Install Dependencies
      run: |
        brew install xcbeautify
        
    - name: Setup Provisioning Profile
      env:
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
        
    - name: Setup Code Signing
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # Create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        
        # Import certificate from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH
        
        # Create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        
        # Import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        
    - name: Build App
      run: |
        xcodebuild -project LightNovelPub.xcodeproj \
          -scheme LightNovelPub \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath build/LightNovelPub.xcarchive \
          clean archive | xcbeautify
          
    - name: Create IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath build/LightNovelPub.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build/Export | xcbeautify
          
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: LightNovelPub
        path: Apps/lightnovelpub/build/Export/LightNovelPub.ipa
