name: LightNovel Pub Build

on:
  push:
    branches: [ main ]
    paths:
      - 'Apps/lightnovelpub/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Apps/lightnovelpub/**'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  BUNDLE_ID: "com.alot1z.lightnovelpub"
  APP_NAME: "LightNovel Pub"
  MIN_IOS: "16.0"
  MAX_IOS: "17.0"

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks $(sysctl -n hw.ncpu)
        
    - name: Cache Build
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/org.swift.swiftpm
          ~/Library/Developer/Xcode/DerivedData
          Apps/lightnovelpub/build
        key: ${{ runner.os }}-build-${{ hashFiles('Apps/lightnovelpub/**') }}
        restore-keys: |
          ${{ runner.os }}-build-
    
    - name: Prepare Build
      run: |
        cd Apps/lightnovelpub
        mkdir -p build/Assets.xcassets/AppIcon.appiconset
        cp assets/Light_Novel_pub_Icon.png build/Assets.xcassets/AppIcon.appiconset/icon.png
        
        # Create Contents.json
        echo '{
          "images": [{"filename": "icon.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"}],
          "info": {"version": 1, "author": "xcode"}
        }' > build/Assets.xcassets/AppIcon.appiconset/Contents.json
        
        # Create Info.plist
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0"><dict>
          <key>CFBundleIdentifier</key><string>'${BUNDLE_ID}'</string>
          <key>CFBundleName</key><string>'${APP_NAME}'</string>
          <key>CFBundleVersion</key><string>1.0.0</string>
          <key>CFBundleShortVersionString</key><string>1.0.0</string>
          <key>MinimumOSVersion</key><string>'${MIN_IOS}'</string>
          <key>UIDeviceFamily</key><array>
            <integer>1</integer>
            <integer>2</integer>
          </array>
          <key>UISupportedInterfaceOrientations</key>
          <array>
            <string>UIInterfaceOrientationPortrait</string>
            <string>UIInterfaceOrientationLandscapeLeft</string>
            <string>UIInterfaceOrientationLandscapeRight</string>
          </array>
          <key>UILaunchStoryboardName</key>
          <string>LaunchScreen</string>
          <key>UIRequiresFullScreen</key>
          <true/>
        </dict></plist>' > build/Info.plist
    
    - name: Build App
      run: |
        cd Apps/lightnovelpub
        
        # Set build environment
        export SWIFT_COMPILATION_MODE=wholemodule
        export SWIFT_OPTIMIZATION_LEVEL=-O
        export SWIFT_USE_PARALLEL_WHOLE_MODULE_OPTIMIZATION=YES
        export SWIFT_PARALLEL_MODULE_JOBS=$(sysctl -n hw.ncpu)
        
        xcodebuild -scheme LightNovelPub \
          -configuration Release \
          -destination generic/platform=iOS \
          -derivedDataPath build/DerivedData \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
          SWIFT_OPTIMIZATION_LEVEL=-O \
          clean build
    
    - name: Create IPA
      run: |
        cd Apps/lightnovelpub
        mkdir -p Payload/LightNovelPub.app
        cp -r build/Release-iphoneos/* Payload/LightNovelPub.app/
        zip -r LightNovelPub.ipa Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: LightNovelPub-IPA
        path: Apps/lightnovelpub/LightNovelPub.ipa
