name: Build LightNovelPub IPA

on:
  push:
    paths:
      - 'Apps/lightnovelpub/**'
      - '.github/workflows/lightnovelpub.yml'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  BUNDLE_ID: "com.alot1z.lightnovelpub"
  APP_NAME: "LightNovel Pub"

jobs:
  build:
    name: Build LightNovelPub IPA
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Set up build directory
      run: |
        mkdir -p build/LightNovelPub.xcarchive/Products/Applications
        
    - name: Build unsigned app
      run: |
        cd Apps/lightnovelpub
        xcodebuild -project LightNovelPub.xcodeproj \
          -scheme LightNovelPub \
          -configuration Release \
          -archivePath ../../build/LightNovelPub.xcarchive \
          -destination 'generic/platform=iOS' \
          -sdk iphoneos \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Package IPA
      run: |
        cd build/LightNovelPub.xcarchive/Products/Applications
        mkdir Payload
        cp -r LightNovelPub.app Payload/
        zip -r LightNovelPub.ipa Payload
        rm -rf Payload
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: LightNovelPub-unsigned
        path: build/LightNovelPub.xcarchive/Products/Applications/LightNovelPub.ipa
        retention-days: 5
