name: 📱 LightNovelPub iOS Build

on:
  push:
    branches: [ main ]
    paths:
      - 'Apps/lightnovelpub/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Apps/lightnovelpub/**'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  BUNDLE_ID: "com.alot1z.lightnovelpub"
  APP_NAME: "LightNovel Pub"
  MIN_IOS: "16.0"
  MAX_IOS: "17.0"

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks $(sysctl -n hw.ncpu)
    
    - name: Prepare Build
      run: |
        cd Apps/lightnovelpub
        mkdir -p build/Assets.xcassets/AppIcon.appiconset
        cp assets/Light_Novel_pub_Icon.png build/Assets.xcassets/AppIcon.appiconset/icon.png
        
        # Create Contents.json
        echo '{
          "images": [{"filename": "icon.png", "idiom": "universal", "platform": "ios", "size": "1024x1024"}],
          "info": {"version": 1, "author": "xcode"}
        }' > build/Assets.xcassets/AppIcon.appiconset/Contents.json
        
        # Create Info.plist
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0"><dict>
          <key>CFBundleIdentifier</key><string>'${BUNDLE_ID}'</string>
          <key>CFBundleName</key><string>'${APP_NAME}'</string>
          <key>CFBundleVersion</key><string>1.0.0</string>
          <key>MinimumOSVersion</key><string>'${MIN_IOS}'</string>
        </dict></plist>' > build/Info.plist
    
    - name: Build App
      run: |
        cd Apps/lightnovelpub
        xcodebuild -scheme LightNovelPub \
          -configuration Release \
          -destination generic/platform=iOS \
          ONLY_ACTIVE_ARCH=NO \
          BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
          SWIFT_OPTIMIZATION_LEVEL=-O \
          clean build
    
    - name: Create IPA
      run: |
        cd Apps/lightnovelpub
        mkdir -p Payload/LightNovelPub.app
        cp -r build/Release-iphoneos/* Payload/LightNovelPub.app/
        zip -r LightNovelPub.ipa Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: LightNovelPub-IPA
        path: Apps/lightnovelpub/LightNovelPub.ipa
