name: LightNovelPub Build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Apps/lightnovelpub/**'
      - '.github/workflows/lightnovelpub.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Apps/lightnovelpub/**'
      - '.github/workflows/lightnovelpub.yml'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  BUNDLE_ID: "com.alot1z.lightnovelpub"
  APP_NAME: "LightNovel Pub"

jobs:
  build:
    name: Build LightNovelPub IPA
    runs-on: macos-latest
    defaults:
      run:
        working-directory: Apps/lightnovelpub

    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Install Dependencies
      run: |
        brew install xcbeautify

    - name: Build App
      run: |
        xcodebuild -project LightNovelPub.xcodeproj \
          -scheme LightNovelPub \
          -configuration Release \
          -destination 'generic/platform=iOS' \
          -archivePath build/LightNovelPub.xcarchive \
          clean archive CODE_SIGNING_ALLOWED=NO | xcbeautify
          
    - name: Create IPA
      run: |
        cd build/LightNovelPub.xcarchive/Products/Applications
        mkdir Payload
        cp -r *.app Payload/
        zip -r LightNovelPub.ipa Payload
        mv LightNovelPub.ipa ../../../
          
    - name: Upload LightNovelPub IPA
      uses: actions/upload-artifact@v4
      with:
        name: LightNovelPub-Unsigned
        path: Apps/lightnovelpub/build/LightNovelPub.ipa
        retention-days: 5
