name: Build TrollStore App

on:
  workflow_dispatch:
  push:
    paths:
      - 'Apps/trollstore/**'
      - '.github/workflows/trollstore.yml'
      - 'tools/root/**'
      - 'Exploits/**'

permissions:
  contents: read
  actions: write

env:
  APP_NAME: TrollStore
  BUNDLE_ID: com.alot1z.trollstore
  MIN_IOS: "16.0"
  MAX_IOS: "17.0"
  TEAM_ID: "ALOT1Z"

jobs:
  build:
    name: Build iOS App
    runs-on: macos-14
    timeout-minutes: 30
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
      
    - name: Setup Build Environment
      run: |
        sudo xcode-select --switch /Applications/Xcode.app
        brew install ldid imagemagick swift || true
      shell: bash
        
    - name: Setup Root Components
      run: |
        # Copy root helper
        mkdir -p Apps/trollstore/src/root
        cp tools/root/giveMeRoot.m Apps/trollstore/src/root/
        
        # Copy exploit files
        mkdir -p Apps/trollstore/src/exploits
        cp -r Exploits/CVE_2023_42824/* Apps/trollstore/src/exploits/
        
        # Merge entitlements
        cat tools/root/root_entitlements.plist > Apps/trollstore/entitlements.plist
      shell: bash
        
    - name: Build ChOma
      run: |
        cd Apps/trollstore/ChOma
        make clean
        make
        cp build/choma ../tools/
      shell: bash
        
    - name: Build Release
      run: |
        cd Apps/trollstore
        chmod +x scripts/*.sh
        
        # Generate icons
        ./scripts/generate_icons.sh \
          --input resources/icon.png \
          --output build/
        
        # Create Info.plist
        ./scripts/create_plist.sh \
          --bundle-id "${{ env.BUNDLE_ID }}" \
          --app-name "${{ env.APP_NAME }}" \
          --app-version "1.0.0" \
          --min-ios-version "${{ env.MIN_IOS }}" \
          --max-ios-version "${{ env.MAX_IOS }}" \
          --output build/Info.plist
        
        # Build app with root and exploit integration
        ./scripts/build.sh \
          --ios-version "${{ env.MAX_IOS }}" \
          --app-version "1.0.0" \
          --min-ios-version "${{ env.MIN_IOS }}" \
          --max-ios-version "${{ env.MAX_IOS }}" \
          --optimization-level 3 \
          --enable-bitcode false \
          --enable-arc true \
          --deployment-target "${{ env.MIN_IOS }}" \
          --build-type release \
          --root-enabled true \
          --exploit-enabled true
        
        # Sign with entitlements
        ./scripts/sign_app.sh \
          --app "build/${{ env.APP_NAME }}.app" \
          --entitlements entitlements.plist
      shell: bash
        
    - name: Package IPA
      run: |
        cd Apps/trollstore/build
        mkdir -p Payload
        cp -r "${{ env.APP_NAME }}.app" Payload/
        zip -r "${{ env.APP_NAME }}.ipa" Payload
        rm -rf Payload
      shell: bash
        
    - name: Upload Release IPA
      uses: actions/upload-artifact@v4
      with:
        name: TrollStore-Release
        path: |
          Apps/trollstore/build/*.ipa
          Apps/trollstore/build/logs/
          Apps/trollstore/build/debug-symbols/
        retention-days: 90
        compression-level: 9
        overwrite: true
